name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest 
    steps:
      - name: Assign label 
        if: contains(github.event.issue.title, 'bug') 
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repos }} \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "label" : ["bug"]
              }' \
          --fail    